#+TITLE: a_music_xml_extract
#+AUTHOR: Paul McCombs
#+EMAIL: paul@lazym8.com
#+DESCRIPTION: Just having a play at parsing and browsing metadata from the Apple Music application on MacOS.
#+OPTIONS: ^:{}

* Introduction

Just having a play at parsing and browsing metadata from the Apple Music application on MacOS.

To get started open Music on your mac and select File->Library->Export Library, then save the file as /Library.xml/ in the directory of this repository for the code as it exists here will find it. I've added ~*.xml~ to /.gitignore/ so that my large metadata file won't be wasting space in the repository.

I'm starting with some Python code I had working several years ago, when Music was still called iTunes.

* Features

Currently the manually saved /Library.xml/ file is parsed with Element Tree in /library_parse_mod.py/ and an artist can be searched using /demo.py/.

** Parse XML
   parse_XML() takes no arguments. It currently loads a hard coded iTunes XML file.
   Checks its version. Uses ElementTree to parse the tree and create a root. Finds
   the Tracks <dict> tag that contains all the song data elements. Creates a iterator.
   Loops through the Tracks <dict> passing the iterator to song_value_dict which
   returns a 3 element tuple. The song_key (int), song_value_dict (dict of attribute
   elements for that song), and a boolean flag that indicates the end of the Tracks
   <dict> and breaks the loop.

   Finally this function returns a two object tuple. First a songs
   dictionary with SongID integers for keys and song attribute dictionaries for
   values. Second a Play List Dictionary with string Names for keys, and set of
   SongIDs for values.
** Demo.py
   Imports library_parse_mod, prompts for a text string and displays a brief summary of each track with an Artist value containing that string. The match is case insensitive.

* Notes about Library.xml
** What is the XML structure?
#+begin_src xml
  <plist version="1.0">
  <dict>
	  <key>Major Version</key><integer>1</integer>
	  <key>Minor Version</key><integer>1</integer>
	  <key>Date</key><date>2025-12-06T04:21:19Z</date>
	  <key>Application Version</key><string>1.5.6.11</string>
	  <key>Features</key><integer>5</integer>
	  <key>Show Content Ratings</key><true/>
	  <key>Music Folder</key><string>file:///Volumes/Glittering/Music_Application_Media/Music/</string>
	  <key>Library Persistent ID</key><string>25292136D4FD2577</string>
	  <key>Tracks</key>
	  <dict>
		  <key>3784</key>
		  <dict>
			  <key>Track ID</key><integer>3784</integer>
			  <key>Name</key><string>Love Among the Ruins</string>
			  <key>Artist</key><string>10,000 Maniacs</string>
			  <key>Album</key><string>Help Yourself</string>
			  <key>Genre</key><string>Pop/Rock</string>
			  <key>Kind</key><string>MPEG audio file</string>
			  <key>Size</key><integer>3857435</integer>
			  <key>Total Time</key><integer>240535</integer>
			  <key>Track Number</key><integer>10</integer>
			  <key>Date Modified</key><date>2007-01-13T18:42:11Z</date>
			  <key>Date Added</key><date>2010-05-25T05:44:10Z</date>
			  <key>Bit Rate</key><integer>128</integer>
			  <key>Sample Rate</key><integer>44100</integer>
			  <key>Play Count</key><integer>17</integer>
			  <key>Play Date</key><integer>3836228360</integer>
			  <key>Play Date UTC</key><date>2025-07-25T01:59:20Z</date>
			  <key>Skip Count</key><integer>1</integer>
			  <key>Skip Date</key><date>2017-01-21T00:58:04Z</date>
			  <key>Normalization</key><integer>3903</integer>
			  <key>Compilation</key><true/>
			  <key>Artwork Count</key><integer>1</integer>
			  <key>Persistent ID</key><string>0A0144BF278979F2</string>
			  <key>Track Type</key><string>File</string>
			  <key>Location</key><string>file:///Volumes/Glittering/Music_Application_Media/Music/Compilations/Help%20Yourself/10%20Love%20Among%20the%20Ruins.mp3</string>
			  <key>File Folder Count</key><integer>4</integer>
			  <key>Library Folder Count</key><integer>1</integer>
		  </dict>
	  </dict>
	  <key>Playlists</key>
	  <array>
		<dict>
			<key>Name</key><string>Library</string>
			<key>Description</key><string></string>
			<key>Master</key><true/>
			<key>Playlist ID</key><integer>62</integer>
			<key>Playlist Persistent ID</key><string>0000000000000005</string>
			<key>Visible</key><false/>
			<key>All Items</key><true/>
			<key>Playlist Items</key>
			<array>
				<dict>
					<key>Track ID</key><integer>3784</integer>
				</dict>
			</array>
		</dict>
	  </array>
  </dict>
  </plist>
#+end_src
** What are we looking for?
   Each song has:
   1. A numeric key:  ~<key>xxxxx</key>~
   2. A dictionary with many composite keys:
      + ~<key>Total Time</key>~:  an integer with milliseconds for units
      + ~<key>Play Date UTC</key>~: a datetime object in UTC but not explicitly noted as such. Needs to be processed to show local time.
